
###########################################################
###########################################################
###########################################################
#docker-compose.yml

version: "3"
services:
    nodebasic:
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ".:/usr/src/app"
            - "/usr/src/app/node_modules"
        ports:
            - '9999:8080'

###########################################################
###########################################################
###########################################################
#Dockerfile
FROM node:8

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "start" ]


###########################################################
###########################################################
###########################################################
#package.json
{
  "name": "docker_web_app",
  "version": "1.0.0",
  "description": "Node.js on Docker",
  "author": "First Last <first.last@example.com>",
  "main": "server.js",
  "scripts": {
    "start": "nodemon server.js"
  },
  "dependencies": {
    "express": "^4.16.1",
    "nodemon": "^1.18.8"
  }
}


###########################################################
###########################################################
###########################################################
#server.js
'use strict';

const express = require('express');

// Constants
const PORT = 8080;
const HOST = '0.0.0.0';

// App
const app = express();
app.get('/', (req, res) => {
  res.send('Hello world car\n');
});

app.listen(PORT, HOST);
console.log(`Running on http://${HOST}:${PORT}`);
