#########################################################
#########################################################
#########################################################
#Dockerfile

FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install Flask==1.0.2
ENTRYPOINT ["python"]
CMD ["app.py"]


#########################################################
#########################################################
#########################################################
#docker-compose.yml

version: "3"
services:
    pyflask:
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ".:/app"
        ports:
            - '9988:5000'

#########################################################
#########################################################
#########################################################
#app.py

from flask import Flask
app = Flask(__name__)

@app.route('/')


def hello_world():
    return 'Flask Dockerized nr 1'

if __name__ == '__main__':
    app.run(debug=True,host='0.0.0.0')
